package com.nobelbiocare.rfid_cabinet;

/**
 * Service implementation of {MI302_SetEvents_Cabinets_oa_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "MI302_SetEvents_Cabinets_oa_Service", targetNamespace = "http://nobelbiocare.com/rfid_cabinet", wsdlLocation = "META-INF/wsdl/com/nobelbiocare/rfid_cabinet/MI302_SetEvents_Cabinets_oa/MI302_SetEvents_Cabinets_oa.wsdl")
public class MI302SetEventsCabinetsOaService extends javax.xml.ws.Service {

  private final static java.net.URL MI302SETEVENTSCABINETSOASERVICE_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public MI302SetEventsCabinetsOaService() throws java.net.MalformedURLException {
    super(MI302SETEVENTSCABINETSOASERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://nobelbiocare.com/rfid_cabinet", "MI302_SetEvents_Cabinets_oa_Service"));
  }
  public MI302SetEventsCabinetsOaService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [MI302_SetEvents_Cabinets_oa_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "MI302_SetEvents_Cabinets_oa_Port")
  public com.nobelbiocare.rfid_cabinet.MI302SetEventsCabinetsOa getMI302_SetEvents_Cabinets_oa_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://nobelbiocare.com/rfid_cabinet","MI302_SetEvents_Cabinets_oa_Port");
    return (com.nobelbiocare.rfid_cabinet.MI302SetEventsCabinetsOa) super.getPort(portName,com.nobelbiocare.rfid_cabinet.MI302SetEventsCabinetsOa.class);
  }
}
