<?xml version="1.0" encoding="UTF-8"?>
<public-part
		 xmlns="http://xml.sap.com/2002/11/PublicPart"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://xml.sap.com/2002/11/PublicPart ppdef.xsd"
		 version="1.0.3"
		 xmlns:IDX="urn:sap.com:PublicPart:1.0">
	<name>gci</name>
	<purpose>compilation</purpose>
	<caption>API for code generated by the Web Dynpro code generator</caption>
	<description>This is not part of the API for appication development! The contents of this public part is intended for code generated by the Web Dynpro code generator. Due to technical limitations the contents is also accessible by application development (i.e. non-generated code). However, it must not be used by application development.</description>
	<entities>
		<entity-ref>
			<dc-ref>
				<name>tc/wd/pack/gci</name>
				<vendor>sap.com</vendor>
			</dc-ref>
			<pp-ref>default</pp-ref>
		</entity-ref>
	</entities>
	<access-control-list>
		<grant>
			<sc-ref>
				<name>*</name>
				<vendor>*</vendor>
			</sc-ref>
		</grant>
	</access-control-list>
</public-part>
